on: [push, pull_request]
name: CI
jobs:
  go-build:
    strategy:
      matrix:
        go-version: [1.16]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build .

  docker-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container
        run: docker build -f Dockerfile .
